### PR TITLE
Fix bin/test-all

### PR DESCRIPTION
**Pull request by ryanplusplus**
This accounts for the changes from https://github.com/exercism/lua/pull/287

### CODE REVIEW

**Comment by imolein** [comment]
I just wondered why the test was failing. I guess this can be merged now?

**Comment by ryanplusplus** [comment]
> I just wondered why the test was failing. I guess this can be merged now?

I can't merge without a review... and unfortunately I'm the only active maintainer for the Lua track. Would you like to become a maintainer? You've been very helpful and it would let you review and merge in addition to your contributions.

**Comment by imolein** [comment]
Yes, sure :)
Since this track and your mentoring taught me a lot while learning a bit of programming with this wonderful language, I'm happy if I can give something back by contributing here and help you out.

**Comment by ryanplusplus** [comment]
Thanks! All you need to do is submit a PR adding yourself to https://github.com/exercism/lua/blob/main/config/maintainers.json. Once I've merged your PR, the Exercism infrastructure should give you commit rights to this repo.

**Review by imolein — APPROVED** [review]
LGTM

**Pull request merged**
